# Generated by Django 3.2.11 on 2022-03-20 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
