# Generated by Django 3.2.11 on 2022-02-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_student_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
