# Generated by Django 3.2.11 on 2022-03-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='student',
        ),
        migrations.RemoveField(
            model_name='account',
            name='teacher',
        ),
    ]
